# Generated by Django 2.1.3 on 2019-05-02 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0001_initial'),
        ('scoreManagement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluationform',
            name='teaching',
        ),
        migrations.AddField(
            model_name='evaluationform',
            name='course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='scoreManagement.Course'),
        ),
        migrations.AddField(
            model_name='evaluationform',
            name='item7',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='evaluationform',
            name='item8',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='evaluationform',
            name='student',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backstage.Student'),
        ),
        migrations.AddField(
            model_name='evaluationform',
            name='sum',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='evaluationform',
            name='teacher',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backstage.Teacher'),
        ),
        migrations.AlterField(
            model_name='evaluationform',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='evaluationform',
            name='is_finish',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='evaluationform',
            name='item1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='evaluationform',
            name='item2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='evaluationform',
            name='item3',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='evaluationform',
            name='item4',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='evaluationform',
            name='item5',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='evaluationform',
            name='item6',
            field=models.IntegerField(default=0),
        ),
    ]
