# Generated by Django 2.1.7 on 2019-04-17 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreManagement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='majorcourses',
            name='course_type',
        ),
        migrations.RemoveField(
            model_name='majorcourses',
            name='score',
        ),
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='score',
            field=models.FloatField(null=True),
        ),
    ]
