# Generated by Django 2.1.7 on 2019-04-20 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0001_initial'),
        ('scoreManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('cno', 'cname', 'college')},
        ),
    ]
