# Generated by Django 2.1.7 on 2019-04-20 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0001_initial'),
        ('scoreManagement', '0002_auto_20190420_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teaching',
            name='tno',
        ),
        migrations.AddField(
            model_name='teaching',
            name='tno',
            field=models.ManyToManyField(to='backstage.Teacher'),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('cno', 'cname', 'course_type')},
        ),
        migrations.AlterUniqueTogether(
            name='coursescore',
            unique_together={('teaching', 'sno')},
        ),
    ]
