# Generated by Django 2.1.3 on 2019-05-02 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreManagement', '0002_auto_20190502_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationform',
            name='description',
            field=models.TextField(default='无'),
        ),
    ]
