# Generated by Django 2.1.7 on 2019-04-17 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreManagement', '0003_auto_20190417_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='id',
        ),
        migrations.AlterField(
            model_name='course',
            name='cno',
            field=models.CharField(max_length=9, primary_key=True, serialize=False),
        ),
    ]
