# Generated by Django 2.1.7 on 2019-04-21 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoreManagement', '0005_auto_20190420_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursescore',
            name='teaching',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoreManagement.Teaching'),
        ),
    ]
