# Generated by Django 2.1.7 on 2019-04-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreManagement', '0006_auto_20190421_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursescore',
            name='commen_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='coursescore',
            name='final_score',
            field=models.FloatField(default=0),
        ),
    ]
