# Generated by Django 2.1.7 on 2019-05-03 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scoreManagement', '0001_initial'),
        ('backstage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule_result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=128)),
                ('sno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backstage.Student')),
                ('tno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoreManagement.Teaching')),
                ('where', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backstage.ClassRoom')),
            ],
            options={
                'db_table': 'Schedule_result',
            },
        ),
        migrations.CreateModel(
            name='Teacher_Schedule_result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=128)),
                ('current_number', models.IntegerField()),
                ('MAX_number', models.IntegerField()),
                ('state', models.CharField(max_length=128)),
                ('tno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoreManagement.Teaching')),
                ('where', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backstage.ClassRoom')),
            ],
            options={
                'db_table': 'Teacher_Schedule_result',
            },
        ),
        migrations.AlterUniqueTogether(
            name='teacher_schedule_result',
            unique_together={('tno', 'where', 'time')},
        ),
        migrations.AlterUniqueTogether(
            name='schedule_result',
            unique_together={('sno', 'tno', 'where', 'time')},
        ),
    ]
