# Generated by Django 2.1.7 on 2019-05-12 08:56

from django.db import migrations, models
import django.db.models.deletion



    initial = True

    dependencies = [
        ('scoreManagement', '0001_initial'),
        ('backstage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom_other_schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(default='', max_length=128)),
                ('crno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backstage.ClassRoom')),
            ],
            options={
                'db_table': 'Classroom_other_schedule',
            },
        ),
        migrations.CreateModel(
            name='Exam_Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'Exam_Schedule',
            },
        ),
        migrations.CreateModel(
            name='Schedule_result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=128)),
                ('sno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backstage.Student')),
                ('tno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoreManagement.Teaching')),
                ('where', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backstage.ClassRoom')),
            ],
            options={
                'db_table': 'Schedule_result',
            },
        ),
        migrations.CreateModel(
            name='Teacher_Schedule_result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=128)),
                ('current_number', models.IntegerField()),
                ('MAX_number', models.IntegerField()),
                ('state', models.CharField(max_length=128)),
                ('tno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoreManagement.Teaching')),
                ('where', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backstage.ClassRoom')),
            ],
            options={
                'db_table': 'Teacher_Schedule_result',
            },
        ),
        migrations.AddField(
            model_name='exam_schedule',
            name='tno_mno_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseScheduling.Teacher_Schedule_result'),
        ),
        migrations.AddField(
            model_name='exam_schedule',
            name='where',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backstage.ClassRoom'),
        ),
        migrations.AlterUniqueTogether(
            name='teacher_schedule_result',
            unique_together={('tno', 'where', 'time')},
        ),
        migrations.AlterUniqueTogether(
            name='schedule_result',
            unique_together={('sno', 'tno', 'where', 'time')},
        ),
    ]
