# Generated by Django 2.1.3 on 2019-05-26 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backstage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalProjectScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backstage.Student')),
            ],
            options={
                'db_table': 'FinalProjectScore',
            },
        ),
        migrations.CreateModel(
            name='GraduationProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=30)),
                ('pdirection', models.CharField(max_length=10)),
                ('pdifficulty', models.CharField(max_length=10)),
                ('pkeywords', models.TextField()),
                ('pdescription', models.TextField()),
                ('pstu', models.TextField()),
                ('pstatus', models.IntegerField(default=0)),
                ('tno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backstage.Teacher')),
            ],
            options={
                'db_table': 'GraduationProject',
            },
        ),
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtype', models.CharField(max_length=10)),
                ('dpath', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'ProjectDocument',
            },
        ),
        migrations.CreateModel(
            name='ProjectScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lundian', models.IntegerField(default=0)),
                ('fangan', models.IntegerField(default=0)),
                ('dabian', models.IntegerField(default=0)),
                ('grade', models.IntegerField(default=0)),
                ('comments', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graduationManagement.ProjectDocument')),
            ],
            options={
                'db_table': 'ProjectScore',
            },
        ),
        migrations.CreateModel(
            name='StuChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('pno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graduationManagement.GraduationProject')),
                ('sno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backstage.Student')),
                ('tno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backstage.Teacher')),
            ],
            options={
                'db_table': 'StuChoice',
            },
        ),
        migrations.AddField(
            model_name='projectdocument',
            name='schoic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graduationManagement.StuChoice'),
        ),
        migrations.AlterUniqueTogether(
            name='stuchoice',
            unique_together={('sno', 'tno', 'pno')},
        ),
    ]
