# Generated by Django 2.1 on 2019-05-09 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backstage', '0001_initial'),
        ('courseScheduling', '0002_auto_20190509_0957'),
    ]

    operations = [
        migrations.CreateModel(
            name='courseSelected',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('cno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseScheduling.Teacher_Schedule_result')),
                ('sno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backstage.Student')),
            ],
            options={
                'db_table': 'courseSelected',
            },
        ),
    ]
