# Generated by Django 2.1.3 on 2019-05-13 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backstage', '__first__'),
        ('scoreManagement', '0001_initial'),
        ('courseSelection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher_schedule_result',
            name='tno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoreManagement.Teaching'),
        ),
        migrations.AddField(
            model_name='courseselected',
            name='cno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseSelection.Teacher_Schedule_result'),
        ),
        migrations.AddField(
            model_name='courseselected',
            name='sno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backstage.Student'),
        ),
        migrations.AlterUniqueTogether(
            name='teacher_schedule_result',
            unique_together={('tno', 'time')},
        ),
    ]
