# Generated by Django 2.1.7 on 2019-05-28 01:30

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'db_table': 'adm_class',
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='通知', max_length=150)),
                ('messages', models.TextField(max_length=150)),
                ('author', models.CharField(max_length=128)),
                ('receiver', models.CharField(choices=[('全体成员', '全体成员'), ('信息科学与技术学院', '信息科学与技术学院'), ('化学工程学院', '化学工程学院'), ('材料科学与工程学院', '材料科学与工程学院'), ('机电工程学院', '机电工程学院'), ('经济管理学院', '经济管理学院'), ('理学院', '理学院'), ('文法学院', '文法学院'), ('生命科学与技术学院', '生命科学与技术学院'), ('继续教育学院', '继续教育学院'), ('马克思主义学院', '马克思主义学院'), ('国际教育学院', '国际教育学院'), ('侯德榜工程师学院', '侯德榜工程师学院'), ('能源学院', '能源学院'), ('巴黎居里工程师学院', '巴黎居里工程师学院'), ('个人', '个人')], default='全体成员', max_length=32)),
                ('year', models.CharField(default='2016', max_length=32)),
                ('visible', models.BooleanField(default=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'announcement',
            },
        ),
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('crno', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('crtype', models.CharField(max_length=10)),
                ('contain_num', models.IntegerField()),
            ],
            options={
                'db_table': 'class_room',
            },
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('short_name', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'db_table': 'college',
            },
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mno', models.CharField(max_length=20, unique=True)),
                ('mname', models.CharField(default='', max_length=128)),
                ('short_name', models.CharField(max_length=20)),
                ('in_college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backstage.College')),
            ],
            options={
                'db_table': 'major',
            },
        ),
        migrations.CreateModel(
            name='MajorPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('cls_num', models.IntegerField()),
                ('people_num', models.IntegerField()),
                ('score_grad', models.IntegerField()),
                ('stu_years', models.IntegerField()),
                ('course_num', models.IntegerField()),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backstage.Major')),
            ],
            options={
                'db_table': 'major_plan',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=128)),
                ('sex', models.BooleanField(default=True)),
                ('score_got', models.IntegerField()),
                ('in_year', models.IntegerField()),
                ('in_cls', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backstage.AdmClass')),
            ],
            options={
                'db_table': 'student',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=128)),
                ('sex', models.BooleanField(default=True)),
                ('in_year', models.IntegerField()),
                ('edu_background', models.CharField(max_length=128, null=True)),
                ('title', models.CharField(default='讲师', max_length=128)),
                ('description', models.TextField(null=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backstage.College')),
            ],
            options={
                'db_table': 'teacher',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UploadFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, default='../backstage/media/image/default.png', null=True, upload_to='files')),
                ('author', models.CharField(max_length=128)),
                ('visible', models.BooleanField(default=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'upload_files',
            },
        ),
        migrations.AddField(
            model_name='admclass',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backstage.MajorPlan'),
        ),
        migrations.AlterUniqueTogether(
            name='majorplan',
            unique_together={('year', 'major')},
        ),
        migrations.AlterUniqueTogether(
            name='major',
            unique_together={('mno', 'mname')},
        ),
    ]
