# Generated by Django 2.1.3 on 2019-04-02 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='通知', max_length=150)),
                ('messages', models.TextField(max_length=150)),
                ('author', models.CharField(max_length=128)),
                ('receiver', models.CharField(choices=[('全体成员', '全体成员'), ('信息科学与技术学院', '信息科学与技术学院'), ('化学工程学院', '化学工程学院'), ('材料科学与工程学院', '材料科学与工程学院'), ('机电工程学院', '机电工程学院'), ('经济管理学院', '经济管理学院'), ('理学院', '理学院'), ('文法学院', '文法学院'), ('生命科学与技术学院', '生命科学与技术学院'), ('继续教育学院', '继续教育学院'), ('马克思主义学院', '马克思主义学院'), ('国际教育学院', '国际教育学院'), ('侯德榜工程师学院', '侯德榜工程师学院'), ('能源学院', '能源学院'), ('巴黎居里工程师学院', '巴黎居里工程师学院'), ('个人', '个人')], default='全体成员', max_length=32)),
                ('year', models.CharField(default='2016', max_length=32)),
                ('visible', models.BooleanField(default=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'announcement',
            },
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.CharField(default='EEE0001', max_length=128, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('type', models.CharField(max_length=128)),
                ('size', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('信息科学与技术学院', '信息科学与技术学院'), ('化学工程学院', '化学工程学院'), ('材料科学与工程学院', '材料科学与工程学院'), ('机电工程学院', '机电工程学院'), ('经济管理学院', '经济管理学院'), ('理学院', '理学院'), ('文法学院', '文法学院'), ('生命科学与技术学院', '生命科学与技术学院'), ('继续教育学院', '继续教育学院'), ('马克思主义学院', '马克思主义学院'), ('国际教育学院', '国际教育学院'), ('侯德榜工程师学院', '侯德榜工程师学院'), ('能源学院', '能源学院'), ('巴黎居里工程师学院', '巴黎居里工程师学院')], default='BUCT', max_length=32, unique=True)),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('length', models.CharField(max_length=128)),
                ('major_plan', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='201600000', max_length=128, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], default='男', max_length=32)),
                ('age', models.CharField(max_length=128)),
                ('start_year', models.CharField(default='2019', max_length=32)),
                ('length', models.CharField(max_length=128)),
                ('mod_data', models.DateTimeField(auto_now=True, verbose_name='Last modified')),
                ('department', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backstage.Dept')),
                ('major', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backstage.Major')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='201600', max_length=128, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=128)),
                ('mod_data', models.DateTimeField(auto_now=True, verbose_name='Last modified')),
                ('department', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backstage.Dept')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='classes',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backstage.Dept'),
        ),
    ]
