# Generated by Django 2.1.7 on 2019-04-21 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='major',
            unique_together={('mno', 'mname')},
        ),
    ]
