INSERT INTO `auth_permission` VALUES (1, 'Can add log entry', 1, 'add_logentry');
INSERT INTO `auth_permission` VALUES (2, 'Can change log entry', 1, 'change_logentry');
INSERT INTO `auth_permission` VALUES (3, 'Can delete log entry', 1, 'delete_logentry');
INSERT INTO `auth_permission` VALUES (4, 'Can view log entry', 1, 'view_logentry');
INSERT INTO `auth_permission` VALUES (5, 'Can add permission', 2, 'add_permission');
INSERT INTO `auth_permission` VALUES (6, 'Can change permission', 2, 'change_permission');
INSERT INTO `auth_permission` VALUES (7, 'Can delete permission', 2, 'delete_permission');
INSERT INTO `auth_permission` VALUES (8, 'Can view permission', 2, 'view_permission');
INSERT INTO `auth_permission` VALUES (9, 'Can add group', 3, 'add_group');
INSERT INTO `auth_permission` VALUES (10, 'Can change group', 3, 'change_group');
INSERT INTO `auth_permission` VALUES (11, 'Can delete group', 3, 'delete_group');
INSERT INTO `auth_permission` VALUES (12, 'Can view group', 3, 'view_group');
INSERT INTO `auth_permission` VALUES (13, 'Can add user', 4, 'add_user');
INSERT INTO `auth_permission` VALUES (14, 'Can change user', 4, 'change_user');
INSERT INTO `auth_permission` VALUES (15, 'Can delete user', 4, 'delete_user');
INSERT INTO `auth_permission` VALUES (16, 'Can view user', 4, 'view_user');
INSERT INTO `auth_permission` VALUES (17, 'Can add content type', 5, 'add_contenttype');
INSERT INTO `auth_permission` VALUES (18, 'Can change content type', 5, 'change_contenttype');
INSERT INTO `auth_permission` VALUES (19, 'Can delete content type', 5, 'delete_contenttype');
INSERT INTO `auth_permission` VALUES (20, 'Can view content type', 5, 'view_contenttype');
INSERT INTO `auth_permission` VALUES (21, 'Can add session', 6, 'add_session');
INSERT INTO `auth_permission` VALUES (22, 'Can change session', 6, 'change_session');
INSERT INTO `auth_permission` VALUES (23, 'Can delete session', 6, 'delete_session');
INSERT INTO `auth_permission` VALUES (24, 'Can view session', 6, 'view_session');
INSERT INTO `auth_permission` VALUES (25, 'Can add adm class', 7, 'add_admclass');
INSERT INTO `auth_permission` VALUES (26, 'Can change adm class', 7, 'change_admclass');
INSERT INTO `auth_permission` VALUES (27, 'Can delete adm class', 7, 'delete_admclass');
INSERT INTO `auth_permission` VALUES (28, 'Can view adm class', 7, 'view_admclass');
INSERT INTO `auth_permission` VALUES (29, 'Can add class room', 8, 'add_classroom');
INSERT INTO `auth_permission` VALUES (30, 'Can change class room', 8, 'change_classroom');
INSERT INTO `auth_permission` VALUES (31, 'Can delete class room', 8, 'delete_classroom');
INSERT INTO `auth_permission` VALUES (32, 'Can view class room', 8, 'view_classroom');
INSERT INTO `auth_permission` VALUES (33, 'Can add college', 9, 'add_college');
INSERT INTO `auth_permission` VALUES (34, 'Can change college', 9, 'change_college');
INSERT INTO `auth_permission` VALUES (35, 'Can delete college', 9, 'delete_college');
INSERT INTO `auth_permission` VALUES (36, 'Can view college', 9, 'view_college');
INSERT INTO `auth_permission` VALUES (37, 'Can add major', 10, 'add_major');
INSERT INTO `auth_permission` VALUES (38, 'Can change major', 10, 'change_major');
INSERT INTO `auth_permission` VALUES (39, 'Can delete major', 10, 'delete_major');
INSERT INTO `auth_permission` VALUES (40, 'Can view major', 10, 'view_major');
INSERT INTO `auth_permission` VALUES (41, 'Can add major plan', 11, 'add_majorplan');
INSERT INTO `auth_permission` VALUES (42, 'Can change major plan', 11, 'change_majorplan');
INSERT INTO `auth_permission` VALUES (43, 'Can delete major plan', 11, 'delete_majorplan');
INSERT INTO `auth_permission` VALUES (44, 'Can view major plan', 11, 'view_majorplan');
INSERT INTO `auth_permission` VALUES (45, 'Can add student', 12, 'add_student');
INSERT INTO `auth_permission` VALUES (46, 'Can change student', 12, 'change_student');
INSERT INTO `auth_permission` VALUES (47, 'Can delete student', 12, 'delete_student');
INSERT INTO `auth_permission` VALUES (48, 'Can view student', 12, 'view_student');
INSERT INTO `auth_permission` VALUES (49, 'Can add teacher', 13, 'add_teacher');
INSERT INTO `auth_permission` VALUES (50, 'Can change teacher', 13, 'change_teacher');
INSERT INTO `auth_permission` VALUES (51, 'Can delete teacher', 13, 'delete_teacher');
INSERT INTO `auth_permission` VALUES (52, 'Can view teacher', 13, 'view_teacher');
INSERT INTO `auth_permission` VALUES (53, 'Can add course', 14, 'add_course');
INSERT INTO `auth_permission` VALUES (54, 'Can change course', 14, 'change_course');
INSERT INTO `auth_permission` VALUES (55, 'Can delete course', 14, 'delete_course');
INSERT INTO `auth_permission` VALUES (56, 'Can view course', 14, 'view_course');
INSERT INTO `auth_permission` VALUES (57, 'Can add course score', 15, 'add_coursescore');
INSERT INTO `auth_permission` VALUES (58, 'Can change course score', 15, 'change_coursescore');
INSERT INTO `auth_permission` VALUES (59, 'Can delete course score', 15, 'delete_coursescore');
INSERT INTO `auth_permission` VALUES (60, 'Can view course score', 15, 'view_coursescore');
INSERT INTO `auth_permission` VALUES (61, 'Can add evaluation form', 16, 'add_evaluationform');
INSERT INTO `auth_permission` VALUES (62, 'Can change evaluation form', 16, 'change_evaluationform');
INSERT INTO `auth_permission` VALUES (63, 'Can delete evaluation form', 16, 'delete_evaluationform');
INSERT INTO `auth_permission` VALUES (64, 'Can view evaluation form', 16, 'view_evaluationform');
INSERT INTO `auth_permission` VALUES (65, 'Can add major courses', 17, 'add_majorcourses');
INSERT INTO `auth_permission` VALUES (66, 'Can change major courses', 17, 'change_majorcourses');
INSERT INTO `auth_permission` VALUES (67, 'Can delete major courses', 17, 'delete_majorcourses');
INSERT INTO `auth_permission` VALUES (68, 'Can view major courses', 17, 'view_majorcourses');
INSERT INTO `auth_permission` VALUES (69, 'Can add teaching', 18, 'add_teaching');
INSERT INTO `auth_permission` VALUES (70, 'Can change teaching', 18, 'change_teaching');
INSERT INTO `auth_permission` VALUES (71, 'Can delete teaching', 18, 'delete_teaching');
INSERT INTO `auth_permission` VALUES (72, 'Can view teaching', 18, 'view_teaching');
INSERT INTO `auth_permission` VALUES (73, 'Can add captcha store', 19, 'add_captchastore');
INSERT INTO `auth_permission` VALUES (74, 'Can change captcha store', 19, 'change_captchastore');
INSERT INTO `auth_permission` VALUES (75, 'Can delete captcha store', 19, 'delete_captchastore');
INSERT INTO `auth_permission` VALUES (76, 'Can view captcha store', 19, 'view_captchastore');
