# Generated by Django 2.1.7 on 2019-04-11 12:54

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'db_table': 'adm_class',
            },
        ),
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('crno', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('crtype', models.CharField(max_length=10)),
                ('contain_num', models.IntegerField()),
            ],
            options={
                'db_table': 'class_room',
            },
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('short_name', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'db_table': 'college',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('cno', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'course',
            },
        ),
        migrations.CreateModel(
            name='CourseForSelect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'course_for_select',
            },
        ),
        migrations.CreateModel(
            name='CourseSelected',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'course_selected',
            },
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mname', models.CharField(max_length=128, unique=True)),
                ('short_name', models.CharField(max_length=10, unique=True)),
                ('gra_score', models.IntegerField()),
                ('in_college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.College')),
            ],
            options={
                'db_table': 'major',
            },
        ),
        migrations.CreateModel(
            name='MajorPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cproper', models.BooleanField(default=True)),
                ('score', models.IntegerField()),
                ('chour', models.IntegerField()),
                ('grade', models.IntegerField()),
                ('semester', models.BooleanField(default=True)),
                ('cno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Course')),
                ('mno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Major')),
            ],
            options={
                'db_table': 'major_plan',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL)),
                ('sno', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('sex', models.BooleanField(default=True)),
                ('score_got', models.IntegerField()),
                ('in_year', models.IntegerField()),
                ('in_cls', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.AdmClass')),
                ('mname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Major')),
            ],
            options={
                'db_table': 'student',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL)),
                ('tno', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('sex', models.BooleanField(default=True)),
                ('in_year', models.IntegerField()),
                ('edu_background', models.CharField(max_length=128, null=True)),
                ('title', models.CharField(default='讲师', max_length=128)),
                ('description', models.TextField(null=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.College')),
            ],
            options={
                'db_table': 'teacher',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Teaching',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('mpno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.MajorPlan')),
                ('tno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Teacher')),
            ],
            options={
                'db_table': 'teaching_table',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Major'),
        ),
        migrations.AddField(
            model_name='admclass',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Major'),
        ),
        migrations.AlterUniqueTogether(
            name='teaching',
            unique_together={('tno', 'mpno')},
        ),
        migrations.AlterUniqueTogether(
            name='majorplan',
            unique_together={('cno', 'mno', 'cproper', 'score', 'chour', 'grade', 'semester')},
        ),
    ]
